### ISSUE TITLE
OMRON HEM-7142T1 project

### ISSUE THREAD

**Issue by stanleyoz** [userx14/omblepy#20]
Hi. Just got a 7142T1 and like to help to connect this device to get the data into our computers. 

In bluetoothctl, was able to pair and connect in "P" mode ..

[bluetooth]# connect F9:28:00:95:99:83 
Attempting to connect to F9:28:00:95:99:83
[CHG] Device F9:28:00:95:99:83 Connected: yes
Connection successful
[CHG] Device F9:28:00:95:99:83 ServicesResolved: yes
[HEM-7142T1]# 

When I ran the omblepy.py script ... 

2023-12-03 11:21:03,341 - omblepy - INFO - unpair and disconnect
Traceback (most recent call last):
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 389, in <module>
    asyncio.run(main())
  File "/home/stanley/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/stanley/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 362, in main
    await bleClient.connect()
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 140, in connect
    raise BleakDeviceNotFoundError(
bleak.exc.BleakDeviceNotFoundError: Device with address F9:28:00:95:99:83 was not found.

OR

2023-12-03 11:26:34,332 - omblepy - INFO - Attempt connecting to F9:28:00:95:99:83.
2023-12-03 11:26:35,752 - omblepy - INFO - unpair and disconnect
Traceback (most recent call last):
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 367, in main
    raise OSError("""Some required bluetooth attributes not found on this ble device. 
OSError: Some required bluetooth attributes not found on this ble device. 
                             This means that either, you connected to a wrong device, 
                             or that your OS has a bug when reading BT LE device attributes (certain linux versions).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 389, in <module>
    asyncio.run(main())
  File "/home/stanley/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/stanley/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 387, in main
    await bleClient.disconnect()
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/__init__.py", line 614, in disconnect
    return await self._backend.disconnect()
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 420, in disconnect
    assert self._bus is None
AssertionError

Is it just a "work-flow" problem here? Should I unpair using bluetoothctl and leave to the script? In what OMRON device "mode" can we recieve data from the device? 

Thanks mate.

**Comment by stanleyoz** [comment]
And ... when my computer is unpaired (I remove the pairing in bluetoothctl), I get this when OMRON is in flashing "P" mode ..

Enter ID or just press Enter to rescan.
0
2023-12-03 11:30:48,211 - omblepy - INFO - Attempt connecting to F9:28:00:95:99:83.
2023-12-03 11:31:18,599 - omblepy - INFO - unpair and disconnect
Traceback (most recent call last):
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 389, in <module>
    asyncio.run(main())
  File "/home/stanley/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/stanley/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/stanley/coding/mkBLE/omblepy/./omblepy.py", line 364, in main
    await bleClient.pair(protection_level = 2)
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/__init__.py", line 629, in pair
    return await self._backend.pair(*args, **kwargs)
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 473, in pair
    assert_reply(reply)
  File "/home/stanley/.local/share/virtualenvs/mkBLE-pJAGQooe/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationCanceled] Authentication Canceled
(mkBLE) (base) stanley@stanLG:~/coding/mkBLE/omblepy$
